#
# Variables 
#
include_common_config := no
#headers_extra := include/asm/offset.h
initrd_modules := kernel/security/capability.ko
#headers_dirs := mips
#build_makeflags := 'V=1 CC=gcc-4.0'
default_config := r4k-ip22
