#
# Variables 
#
include_common_config := no
#headers_extra := include/asm/offset.h
initrd_modules := kernel/security/capability.ko
headers_dirs := mips
#build_makeflags := 'V=1 CC=gcc-3.3'
default_config := r4k-kn04
