#!/bin/bash -e

aufs_dir="$1"

for patch in aufs3-{base,kbuild,standalone}.patch; do
    sed 's/^+.*EXPORT_SYMBOL\b/&_GPL/' < "$aufs_dir"/"$patch" \
	> debian/patches/features/all/aufs3/"$patch"
done

{
    cd "$aufs_dir" &&						\
	{ find Documentation fs -type f;			\
	  ls include/{uapi/,}linux/aufs_type.h; } |		\
	LC_ALL=C sort |						\
	while read file; do
	    diff -uN a/"$file" "$file" | filterdiff --addnewprefix=b/
	done
} > debian/patches/features/all/aufs3/aufs3-add.patch
