PROGS = modpost.real-$(TYPE)

include ../Makefile.inc

modpost.real-$(TYPE): file2alias.real-$(TYPE).o modpost.real-$(TYPE).o sumversion.real-$(TYPE).o
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $^

%.real-$(TYPE).o: $(SOURCEDIR)/%.c
	$(CC) -I real-$(TYPE) $(CFLAGS) -c -o $@ $^

