#!/bin/sh
patch="$1"

error() {
  echo "$@";
  exit 1
}

version=$(filterdiff -p 1 -i Makefile "$patch" | grep "+EXTRAVERSION" | sed -e 's,.*-vs,vs,')
[ "$version" ] || error "can't find version!"

file="$(dirname $0)/$version.patch"

filterdiff -p 1 -x Makefile "$patch" | grep -v "^diff" > "$file"
