#! /bin/sh

debian_series=debian/patches/series-rt
rt_series="$(mktemp)"

trap 'rm "$rt_series"' INT QUIT EXIT

# Remove comments and empty lines. Reformat to match series format.
sed -r -e 's/ *#.*//; /^$/d; s,.*,features/all/rt/&,' "debian/patches/features/all/rt/series" > "$rt_series"

# removed lines are OK if the rt patch contains fixes that are applied on
# featureset=none kernels, too.
diff -u --label "debian/patches/features/all/rt/series" "$rt_series" "$debian_series"
