#!/bin/sh

# Add directory prefix to all filenames, but leave comments and
# empty lines unchanged.
sed -r -e 's,^[^# \t],features/all/rt/&,' "debian/patches/features/all/rt/series" > debian/patches/series-rt
