#! /bin/sh

set -e

version="$1"

if [ -z "$version" ]; then
    echo >&2 "Usage: $0 <version>"
    exit 2
fi

name="patch-$version.patch"
dir="debian/patches/features/all/rt"

basever="$(expr "$version" : '\([3-9].[0-9]*\)')"

wget -O "$dir/$name.bz2" "http://www.kernel.org/pub/linux/kernel/projects/rt/$basever/patch-$version.patch.bz2"
wget -O "$dir/$name.sign" "http://www.kernel.org/pub/linux/kernel/projects/rt/$basever/patch-$version.patch.sign"
bzcat "$dir/$name.bz2" | gpg --verify "$dir/$name.sign" -
bzcat "$dir/$name.bz2" | filterdiff -x 'linux-*/localversion-rt' > "$dir/$name"
