#! /bin/sh

set -e

version="$1"

if [ -z "$version" ]; then
    echo >&2 "Usage: $0 <version>"
    exit 2
fi

name="patch-$version.patch"
dir="debian/patches/features/all/rt"
wget -O "$dir/$name.bz2" "http://www.kernel.org/pub/linux/kernel/projects/rt/patch-$version.patch.bz2"
wget -O "$dir/$name.bz2.sign" "http://www.kernel.org/pub/linux/kernel/projects/rt/patch-$version.patch.bz2.sign"
( cd "$dir" && gpg --verify "$name.bz2.sign" )
bzcat "$dir/$name.bz2" | filterdiff -x linux-2.6/localversion-rt > "$dir/$name"
