#!/bin/sh
set -e
vserverpatch="$1"

error() {
  echo "$@";
  exit 1
}

[ "$vserverpatch" ] || error "please specify the reference vserver patch"

patch="$(dirname $0)/vserver-update.patch"
root="$(dirname $0)/../../../../.."
source="$root/debian/build/source-amd64-xen-vserver-patch"

make -C "$root" -f debian/rules debian/stamps
make -C "$root" -f debian/rules.gen source-amd64-xen
rm -rf "$source"
cp -al "$root/debian/build/source-amd64-xen" "$source"

for i in $(cd "$source"; find arch/i386 arch/x86_64 -name '*-xen.[chS]'); do
  f=${i/-xen/};
  filterdiff -p 1 -i "$f" "$vserverpatch" | patch -d "$source" --no-backup-if-mismatch -F 0 -p 1 $i
done
(cd "$source/.."; diff -ur source-amd64-xen/arch source-amd64-xen-vserver-patch/arch) > "$patch"
