PROGS = \
	bin2c \
	conmakehash \
	kallsyms \
	pnmtologo

DATA = \
	Kbuild.include \
	Makefile.build \
	Makefile.clean \
	Makefile.host \
	Makefile.lib \
	Makefile.modinst \
	Makefile.modpost \
	mkversion

SCRIPTS =  \
	checkincludes.pl \
	checkstack.pl \
	checkversion.pl \
	gcc-version.sh \
	gcc-x86_64-has-stack-protector.sh \
	gen_initramfs_list.sh \
	kernel-doc \
	Lindent \
	makelst \
	mksysmap \
	mkuboot.sh \
	namespace.pl \
	patch-kernel \
	setlocalversion \
	ver_linux

SUBDIRS = \
	basic \
	genksyms \
	kconfig \
	mod

VPATH = $(top_srcdir)/scripts

include Makefile.inc
